### ISSUE TITLE
Pls ensure share all quizes like before

### ISSUE THREAD

**Issue by johnfelipe** [dennislamcv1/IBM-AI-Engineering#1]

**Comment by johnfelipe** [comment]
pls upload all quizes

**Comment by johnfelipe** [comment]
https://gist.github.com/da597505cae7e3ec956ef1a1cd2603cd

can u update final quiz?

**Comment by johnfelipe** [comment]
pls upload final quiz
![SNAG-0115](https://user-images.githubusercontent.com/428820/183901180-5bc03393-a00a-42b7-a255-27bb30113ee3.png)

is still remaining

**Comment by dennislamcv1** [comment]
OK later I take a look

**Comment by dennislamcv1** [comment]
All uploaded, questions may have changed this year
